###
GET http://localhost:8080/annotated/test1/200

###
GET http://localhost:8080/functional/test2

###
GET http://localhost:8080/annotated/test1/100?version-param=1.1

###
GET http://localhost:8080/annotated/test1/100
My-Version: 1.1

###
GET http://localhost:8080/annotated/test1/100
Accept: application/json;mediatype-version=1.1

###
GET http://localhost:8080/annotated/test1/100?version-param=1.2

###
GET http://localhost:8080/annotated/test1/100
My-Version: 1.2

###
GET http://localhost:8080/annotated/test1/100
Accept: application/json;mediatype-version=1.2


###
GET http://localhost:8080/annotated/test1/100?version-param=1.3

###
GET http://localhost:8080/annotated/test1/100
My-Version: 1.3


###
GET http://localhost:8080/functional/test2?version-param=1.2

###
GET http://localhost:8080/functional/test2
My-Version: 1.2

###
GET http://localhost:8080/functional/test2
Accept: application/json;mediatype-version=1.2


###
GET http://localhost:8080/functional/test2?version-param=1.1

###
GET http://localhost:8080/functional/test2
My-Version: 1.1

###
GET http://localhost:8080/functional/test2
Accept: application/json;mediatype-version=1.1

###
GET http://localhost:8080/functional/test2?version-param=1.3

###
GET http://localhost:8080/functional/test2
My-Version: 1.3

###